auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  instance_addr: "::"
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 500

limits_config:
  allow_structured_metadata: true
  max_entries_limit_per_query: 300000
  max_query_length: 720h
  max_query_parallelism: 64
  max_streams_per_user: 50000
  max_line_size: 1000000
  ingestion_rate_mb: 2000
  ingestion_burst_size_mb: 4000
  per_stream_rate_limit: 100MB
  per_stream_rate_limit_burst: 200MB
  reject_old_samples: true
  reject_old_samples_max_age: 720h
  max_query_series: 1000000
  split_queries_by_interval: 24h
  max_cache_freshness_per_query: 10m
  retention_period: 720h

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

pattern_ingester:
  enabled: true

ruler:
  alertmanager_url: http://localhost:9093

frontend:
  encoding: protobuf

compactor:
  working_directory: /tmp/loki/compactor
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 20
  compaction_interval: 10m
  delete_request_store: filesystem
